/** Communes de Kinshasa (24) */
export const KINSHASA_COMMUNES = [
  "Bandalungwa",
  "Barumbu",
  "Bumbu",
  "Gombe",
  "Kalamu",
  "Kasa-Vubu",
  "Kimbanseke",
  "Kinshasa",
  "Kintambo",
  "Kisenso",
  "Lemba",
  "Limete",
  "Lingwala",
  "Makala",
  "Maluku",
  "Masina",
  "Matete",
  "Mont-Ngafula",
  "Ndjili",
  "Ngaba",
  "Ngaliema",
  "Ngiri-Ngiri",
  "Selembao",
] as const;

export type KinshasaCommune = (typeof KINSHASA_COMMUNES)[number];

/** Pays Afrique + Europe avec villes principales */
export const COUNTRIES_CITIES: Record<string, string[]> = {
  "Afrique du Sud": ["Johannesburg", "Le Cap", "Durban", "Pretoria"],
  Algérie: ["Alger", "Oran", "Constantine", "Annaba"],
  Angola: ["Luanda", "Lobito", "Huambo"],
  Bénin: ["Cotonou", "Porto-Novo", "Parakou"],
  Botswana: ["Gaborone", "Francistown"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso"],
  Burundi: ["Bujumbura", "Gitega"],
  Cameroun: ["Douala", "Yaoundé", "Bafoussam"],
  "Cap-Vert": ["Praia", "Mindelo"],
  "République centrafricaine": ["Bangui"],
  Tchad: ["N'Djamena", "Moundou"],
  Comores: ["Moroni"],
  Congo: ["Brazzaville", "Pointe-Noire", "Dolisie"],
  "République démocratique du Congo": ["Kinshasa", "Lubumbashi", "Goma", "Kisangani", "Mbuji-Mayi"],
  "Côte d'Ivoire": ["Abidjan", "Bouaké", "Yamoussoukro"],
  Djibouti: ["Djibouti"],
  Égypte: ["Le Caire", "Alexandrie", "Gizeh"],
  "Guinée équatoriale": ["Malabo"],
  Érythrée: ["Asmara"],
  Eswatini: ["Mbabane"],
  Éthiopie: ["Addis-Abeba", "Dire Dawa"],
  Gabon: ["Libreville", "Port-Gentil"],
  Gambie: ["Banjul"],
  Ghana: ["Accra", "Kumasi", "Tamale"],
  Guinée: ["Conakry", "Kankan"],
  "Guinée-Bissau": ["Bissau"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu"],
  Lesotho: ["Maseru"],
  Liberia: ["Monrovia"],
  Libye: ["Tripoli", "Benghazi"],
  Madagascar: ["Antananarivo", "Toamasina"],
  Malawi: ["Lilongwe", "Blantyre"],
  Mali: ["Bamako", "Sikasso"],
  Maroc: ["Casablanca", "Rabat", "Marrakech", "Fès"],
  Maurice: ["Port-Louis"],
  Mauritanie: ["Nouakchott"],
  Mozambique: ["Maputo", "Beira"],
  Namibie: ["Windhoek"],
  Niger: ["Niamey", "Zinder"],
  Nigeria: ["Lagos", "Abuja", "Kano", "Port Harcourt"],
  Ouganda: ["Kampala", "Entebbe"],
  Rwanda: ["Kigali", "Butare"],
  "São Tomé-et-Principe": ["São Tomé"],
  Sénégal: ["Dakar", "Thiès", "Saint-Louis"],
  Seychelles: ["Victoria"],
  "Sierra Leone": ["Freetown"],
  Somalie: ["Mogadiscio"],
  Soudan: ["Khartoum"],
  "Soudan du Sud": ["Djouba"],
  Tanzanie: ["Dar es Salaam", "Dodoma", "Arusha"],
  Togo: ["Lomé", "Kara"],
  Tunisie: ["Tunis", "Sfax", "Sousse"],
  Zambie: ["Lusaka", "Ndola"],
  Zimbabwe: ["Harare", "Bulawayo"],
  Allemagne: ["Berlin", "Munich", "Francfort", "Hambourg", "Cologne"],
  Autriche: ["Vienne", "Graz", "Salzbourg"],
  Belgique: ["Bruxelles", "Anvers", "Liège", "Gand"],
  Bulgarie: ["Sofia", "Plovdiv", "Varna"],
  Croatie: ["Zagreb", "Split", "Dubrovnik"],
  Danemark: ["Copenhague", "Aarhus", "Odense"],
  Espagne: ["Madrid", "Barcelone", "Valence", "Séville"],
  Estonie: ["Tallinn", "Tartu"],
  Finlande: ["Helsinki", "Tampere", "Turku"],
  France: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Bordeaux"],
  Grèce: ["Athènes", "Thessalonique"],
  Hongrie: ["Budapest", "Debrecen"],
  Irlande: ["Dublin", "Cork", "Galway"],
  Italie: ["Rome", "Milan", "Naples", "Turin", "Florence"],
  Lettonie: ["Riga"],
  Lituanie: ["Vilnius", "Kaunas"],
  Luxembourg: ["Luxembourg"],
  Malte: ["La Valette"],
  "Pays-Bas": ["Amsterdam", "Rotterdam", "La Haye"],
  Pologne: ["Varsovie", "Cracovie", "Gdansk", "Wroclaw"],
  Portugal: ["Lisbonne", "Porto", "Faro"],
  "République tchèque": ["Prague", "Brno"],
  Roumanie: ["Bucarest", "Cluj-Napoca", "Timisoara"],
  "Royaume-Uni": ["Londres", "Manchester", "Birmingham", "Édimbourg"],
  Serbie: ["Belgrade", "Novi Sad"],
  Slovaquie: ["Bratislava", "Kosice"],
  Slovénie: ["Ljubljana"],
  Suède: ["Stockholm", "Göteborg", "Malmö"],
  Suisse: ["Zurich", "Genève", "Bâle", "Berne"],
  Ukraine: ["Kiev", "Lviv", "Odessa"],
};

export const COUNTRY_NAMES = Object.keys(COUNTRIES_CITIES).sort((a, b) =>
  a.localeCompare(b, "fr"),
);

export function getCitiesForCountry(country: string): string[] {
  return COUNTRIES_CITIES[country] ?? [];
}
